// Use the types to define the NAV_LINKS array
export const NAV_LINKS: NavLink[] = [
  {
    id: 1,
    title: "Hello",
    href: "/",
    type: "link",
  },
  { id: 2, title: "About Me", href: "/about", type: "link" },
  { id: 3, title: "Projects", href: "/projects", type: "link" },
];

export const products = [
  {
    id: "ps5-vr2",
    category: "Gaming",
    title: "Sony PlayStation VR2 Headset, 110° FOV, 4K HDR Display",
    rating: 4.8,
    price: 575_000,
    oldPrice: 600_000,
    thumbnail: "/images/shop/hero.svg",
    href: "/shop/products/ps5-vr2",
    description:
      "Immerse yourself in next-level gaming with the Sony PlayStation VR2. Featuring an approximate 110° field of view, this advanced virtual reality headset delivers stunning visuals and unparalleled immersion. Seamlessly integrates with your PS5 for smooth communication and effortless setup.",
    specs: [
      { label: "Display", value: "4K HDR OLED" },
      { label: "Refresh Rate", value: "120Hz" },
      { label: "Field of View", value: "110 degrees" },
      { label: "Controllers", value: "2x PS VR2 Sense" },
      { label: "Tracking", value: "Inside-out" },
      { label: "Connection", value: "USB-C to PS5" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 128,
    stock: 5,
    similarProducts: ["macbook-pro-m2", "iphone-15-pro", "samsung-qled-tv"],
  },
  {
    id: "macbook-pro-m2",
    category: "Gaming",
    title: 'Apple MacBook Pro 14" M2 Pro, 32GB RAM, 1TB SSD',
    rating: 4.9,
    price: 1_850_000,
    oldPrice: 1_999_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/macbook-pro-m2",
    description:
      "Experience unprecedented power with the new MacBook Pro featuring M2 Pro chip. Perfect for professionals and creators who demand the ultimate in performance. Features a stunning Liquid Retina XDR display and exceptional battery life.",
    specs: [
      { label: "Processor", value: "M2 Pro" },
      { label: "RAM", value: "32GB Unified" },
      { label: "Storage", value: "1TB SSD" },
      { label: "Display", value: '14" Liquid Retina XDR' },
      { label: "Battery", value: "Up to 18 hours" },
      { label: "Ports", value: "3x Thunderbolt 4, HDMI, SD" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 89,
    stock: 3,
    similarProducts: ["macbook-pro-m2", "sony-wh1000xm5", "samsung-qled-tv"],
  },
  {
    id: "iphone-15-pro",
    category: "Gaming",
    title: "iPhone 15 Pro Max, 256GB, Titanium Black",
    rating: 4.7,
    price: 989_000,
    oldPrice: 1_050_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/iphone-15-pro",
    description:
      "The most advanced iPhone ever. Featuring a titanium design, A17 Pro chip, and a revolutionary 48MP camera system. Experience the power of Apple's latest innovations with the stunning Super Retina XDR display.",
    specs: [
      { label: "Display", value: '6.7" OLED' },
      { label: "Processor", value: "A17 Pro" },
      { label: "Storage", value: "256GB" },
      { label: "Camera", value: "48MP Main + 12MP Ultra Wide" },
      { label: "Battery", value: "4422mAh" },
      { label: "Material", value: "Titanium frame" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 256,
    stock: 10,
    similarProducts: ["ps5-vr2", "sony-wh1000xm5", "iphone-15-pro"],
  },
  {
    id: "samsung-qled-tv",
    category: "Gaming",
    title: 'Samsung Neo QLED 8K 75", QN900C Smart TV',
    rating: 4.6,
    price: 2_450_000,
    oldPrice: 2_800_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/samsung-qled-8k",
    description:
      "Transform your viewing experience with Samsung's flagship Neo QLED 8K TV. Features Quantum Matrix Technology Pro for precise lighting control and Neural Quantum Processor 8K for unmatched upscaling performance.",
    specs: [
      { label: "Resolution", value: "8K (7680 x 4320)" },
      { label: "Screen Size", value: "75 inches" },
      { label: "HDR", value: "Quantum HDR 4000" },
      { label: "Refresh Rate", value: "120Hz" },
      { label: "Audio", value: "Dolby Atmos" },
      { label: "Smart Platform", value: "Tizen OS" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 45,
    stock: 2,
    similarProducts: ["iphone-15-pro", "macbook-pro-m2", "ps5-vr2"],
  },
  {
    id: "sony-wh1000xm5",
    category: "Gaming",
    title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    rating: 4.8,
    price: 285_000,
    oldPrice: 320_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/sony-wh1000xm5",
    description:
      "Industry-leading noise cancellation meets premium sound quality. The WH-1000XM5 features advanced processors for unprecedented noise cancellation, crystal clear calls, and up to 30 hours of battery life.",
    specs: [
      { label: "Driver", value: "30mm Carbon Fiber" },
      { label: "Battery Life", value: "30 hours" },
      { label: "Charging", value: "USB-C Fast Charging" },
      { label: "Bluetooth", value: "5.2" },
      { label: "Weight", value: "250g" },
      { label: "Codecs", value: "LDAC, AAC, SBC" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 167,
    stock: 15,
    similarProducts: ["iphone-15-pro", "macbook-pro-m2", "ps5-vr2"],
  },
  {
    id: "ps5-vr2",
    category: "Gaming",
    title: "Sony PlayStation VR2 Headset, 110° FOV, 4K HDR Display",
    rating: 4.8,
    price: 575_000,
    oldPrice: 600_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/ps5-vr2",
    description:
      "Immerse yourself in next-level gaming with the Sony PlayStation VR2. Featuring an approximate 110° field of view, this advanced virtual reality headset delivers stunning visuals and unparalleled immersion. Seamlessly integrates with your PS5 for smooth communication and effortless setup.",
    specs: [
      { label: "Display", value: "4K HDR OLED" },
      { label: "Refresh Rate", value: "120Hz" },
      { label: "Field of View", value: "110 degrees" },
      { label: "Controllers", value: "2x PS VR2 Sense" },
      { label: "Tracking", value: "Inside-out" },
      { label: "Connection", value: "USB-C to PS5" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 128,
    stock: 5,
    similarProducts: ["macbook-pro-m2", "iphone-15-pro", "samsung-qled-tv"],
  },
  {
    id: "macbook-pro-m2",
    category: "Gaming",
    title: 'Apple MacBook Pro 14" M2 Pro, 32GB RAM, 1TB SSD',
    rating: 4.9,
    price: 1_850_000,
    oldPrice: 1_999_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/macbook-pro-m2",
    description:
      "Experience unprecedented power with the new MacBook Pro featuring M2 Pro chip. Perfect for professionals and creators who demand the ultimate in performance. Features a stunning Liquid Retina XDR display and exceptional battery life.",
    specs: [
      { label: "Processor", value: "M2 Pro" },
      { label: "RAM", value: "32GB Unified" },
      { label: "Storage", value: "1TB SSD" },
      { label: "Display", value: '14" Liquid Retina XDR' },
      { label: "Battery", value: "Up to 18 hours" },
      { label: "Ports", value: "3x Thunderbolt 4, HDMI, SD" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 89,
    stock: 3,
    similarProducts: ["macbook-pro-m2", "sony-wh1000xm5", "samsung-qled-tv"],
  },
  {
    id: "iphone-15-pro",
    category: "Gaming",
    title: "iPhone 15 Pro Max, 256GB, Titanium Black",
    rating: 4.7,
    price: 989_000,
    oldPrice: 1_050_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/iphone-15-pro",
    description:
      "The most advanced iPhone ever. Featuring a titanium design, A17 Pro chip, and a revolutionary 48MP camera system. Experience the power of Apple's latest innovations with the stunning Super Retina XDR display.",
    specs: [
      { label: "Display", value: '6.7" OLED' },
      { label: "Processor", value: "A17 Pro" },
      { label: "Storage", value: "256GB" },
      { label: "Camera", value: "48MP Main + 12MP Ultra Wide" },
      { label: "Battery", value: "4422mAh" },
      { label: "Material", value: "Titanium frame" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 256,
    stock: 10,
    similarProducts: ["ps5-vr2", "sony-wh1000xm5", "iphone-15-pro"],
  },
  {
    id: "samsung-qled-tv",
    category: "Gaming",
    title: 'Samsung Neo QLED 8K 75", QN900C Smart TV',
    rating: 4.6,
    price: 2_450_000,
    oldPrice: 2_800_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/samsung-qled-8k",
    description:
      "Transform your viewing experience with Samsung's flagship Neo QLED 8K TV. Features Quantum Matrix Technology Pro for precise lighting control and Neural Quantum Processor 8K for unmatched upscaling performance.",
    specs: [
      { label: "Resolution", value: "8K (7680 x 4320)" },
      { label: "Screen Size", value: "75 inches" },
      { label: "HDR", value: "Quantum HDR 4000" },
      { label: "Refresh Rate", value: "120Hz" },
      { label: "Audio", value: "Dolby Atmos" },
      { label: "Smart Platform", value: "Tizen OS" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 45,
    stock: 2,
    similarProducts: ["iphone-15-pro", "macbook-pro-m2", "ps5-vr2"],
  },
  {
    id: "sony-wh1000xm5",
    category: "Gaming",
    title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    rating: 4.8,
    price: 285_000,
    oldPrice: 320_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/sony-wh1000xm5",
    description:
      "Industry-leading noise cancellation meets premium sound quality. The WH-1000XM5 features advanced processors for unprecedented noise cancellation, crystal clear calls, and up to 30 hours of battery life.",
    specs: [
      { label: "Driver", value: "30mm Carbon Fiber" },
      { label: "Battery Life", value: "30 hours" },
      { label: "Charging", value: "USB-C Fast Charging" },
      { label: "Bluetooth", value: "5.2" },
      { label: "Weight", value: "250g" },
      { label: "Codecs", value: "LDAC, AAC, SBC" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 167,
    stock: 15,
    similarProducts: ["iphone-15-pro", "macbook-pro-m2", "ps5-vr2"],
  },
  {
    id: "ps5-vr2",
    category: "Gaming",
    title: "Sony PlayStation VR2 Headset, 110° FOV, 4K HDR Display",
    rating: 4.8,
    price: 575_000,
    oldPrice: 600_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/ps5-vr2",
    description:
      "Immerse yourself in next-level gaming with the Sony PlayStation VR2. Featuring an approximate 110° field of view, this advanced virtual reality headset delivers stunning visuals and unparalleled immersion. Seamlessly integrates with your PS5 for smooth communication and effortless setup.",
    specs: [
      { label: "Display", value: "4K HDR OLED" },
      { label: "Refresh Rate", value: "120Hz" },
      { label: "Field of View", value: "110 degrees" },
      { label: "Controllers", value: "2x PS VR2 Sense" },
      { label: "Tracking", value: "Inside-out" },
      { label: "Connection", value: "USB-C to PS5" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 128,
    stock: 5,
    similarProducts: ["macbook-pro-m2", "iphone-15-pro", "samsung-qled-tv"],
  },
  {
    id: "macbook-pro-m2",
    category: "Gaming",
    title: 'Apple MacBook Pro 14" M2 Pro, 32GB RAM, 1TB SSD',
    rating: 4.9,
    price: 1_850_000,
    oldPrice: 1_999_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/macbook-pro-m2",
    description:
      "Experience unprecedented power with the new MacBook Pro featuring M2 Pro chip. Perfect for professionals and creators who demand the ultimate in performance. Features a stunning Liquid Retina XDR display and exceptional battery life.",
    specs: [
      { label: "Processor", value: "M2 Pro" },
      { label: "RAM", value: "32GB Unified" },
      { label: "Storage", value: "1TB SSD" },
      { label: "Display", value: '14" Liquid Retina XDR' },
      { label: "Battery", value: "Up to 18 hours" },
      { label: "Ports", value: "3x Thunderbolt 4, HDMI, SD" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 89,
    stock: 3,
    similarProducts: ["macbook-pro-m2", "sony-wh1000xm5", "samsung-qled-tv"],
  },
  {
    id: "iphone-15-pro",
    category: "Gaming",
    title: "iPhone 15 Pro Max, 256GB, Titanium Black",
    rating: 4.7,
    price: 989_000,
    oldPrice: 1_050_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/iphone-15-pro",
    description:
      "The most advanced iPhone ever. Featuring a titanium design, A17 Pro chip, and a revolutionary 48MP camera system. Experience the power of Apple's latest innovations with the stunning Super Retina XDR display.",
    specs: [
      { label: "Display", value: '6.7" OLED' },
      { label: "Processor", value: "A17 Pro" },
      { label: "Storage", value: "256GB" },
      { label: "Camera", value: "48MP Main + 12MP Ultra Wide" },
      { label: "Battery", value: "4422mAh" },
      { label: "Material", value: "Titanium frame" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 256,
    stock: 10,
    similarProducts: ["ps5-vr2", "sony-wh1000xm5", "iphone-15-pro"],
  },
  {
    id: "samsung-qled-tv",
    category: "Gaming",
    title: 'Samsung Neo QLED 8K 75", QN900C Smart TV',
    rating: 4.6,
    price: 2_450_000,
    oldPrice: 2_800_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/samsung-qled-8k",
    description:
      "Transform your viewing experience with Samsung's flagship Neo QLED 8K TV. Features Quantum Matrix Technology Pro for precise lighting control and Neural Quantum Processor 8K for unmatched upscaling performance.",
    specs: [
      { label: "Resolution", value: "8K (7680 x 4320)" },
      { label: "Screen Size", value: "75 inches" },
      { label: "HDR", value: "Quantum HDR 4000" },
      { label: "Refresh Rate", value: "120Hz" },
      { label: "Audio", value: "Dolby Atmos" },
      { label: "Smart Platform", value: "Tizen OS" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 45,
    stock: 2,
    similarProducts: ["iphone-15-pro", "macbook-pro-m2", "ps5-vr2"],
  },
  {
    id: "sony-wh1000xm5",
    category: "Gaming",
    title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    rating: 4.8,
    price: 285_000,
    oldPrice: 320_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/sony-wh1000xm5",
    description:
      "Industry-leading noise cancellation meets premium sound quality. The WH-1000XM5 features advanced processors for unprecedented noise cancellation, crystal clear calls, and up to 30 hours of battery life.",
    specs: [
      { label: "Driver", value: "30mm Carbon Fiber" },
      { label: "Battery Life", value: "30 hours" },
      { label: "Charging", value: "USB-C Fast Charging" },
      { label: "Bluetooth", value: "5.2" },
      { label: "Weight", value: "250g" },
      { label: "Codecs", value: "LDAC, AAC, SBC" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 167,
    stock: 15,
    similarProducts: ["iphone-15-pro", "macbook-pro-m2", "ps5-vr2"],
  },
  {
    id: "ps5-vr2",
    category: "Gaming",
    title: "Sony PlayStation VR2 Headset, 110° FOV, 4K HDR Display",
    rating: 4.8,
    price: 575_000,
    oldPrice: 600_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/ps5-vr2",
    description:
      "Immerse yourself in next-level gaming with the Sony PlayStation VR2. Featuring an approximate 110° field of view, this advanced virtual reality headset delivers stunning visuals and unparalleled immersion. Seamlessly integrates with your PS5 for smooth communication and effortless setup.",
    specs: [
      { label: "Display", value: "4K HDR OLED" },
      { label: "Refresh Rate", value: "120Hz" },
      { label: "Field of View", value: "110 degrees" },
      { label: "Controllers", value: "2x PS VR2 Sense" },
      { label: "Tracking", value: "Inside-out" },
      { label: "Connection", value: "USB-C to PS5" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 128,
    stock: 5,
    similarProducts: ["macbook-pro-m2", "iphone-15-pro", "samsung-qled-tv"],
  },
  {
    id: "macbook-pro-m2",
    category: "Gaming",
    title: 'Apple MacBook Pro 14" M2 Pro, 32GB RAM, 1TB SSD',
    rating: 4.9,
    price: 1_850_000,
    oldPrice: 1_999_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/macbook-pro-m2",
    description:
      "Experience unprecedented power with the new MacBook Pro featuring M2 Pro chip. Perfect for professionals and creators who demand the ultimate in performance. Features a stunning Liquid Retina XDR display and exceptional battery life.",
    specs: [
      { label: "Processor", value: "M2 Pro" },
      { label: "RAM", value: "32GB Unified" },
      { label: "Storage", value: "1TB SSD" },
      { label: "Display", value: '14" Liquid Retina XDR' },
      { label: "Battery", value: "Up to 18 hours" },
      { label: "Ports", value: "3x Thunderbolt 4, HDMI, SD" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 89,
    stock: 3,
    similarProducts: ["macbook-pro-m2", "sony-wh1000xm5", "samsung-qled-tv"],
  },
  {
    id: "iphone-15-pro",
    category: "Gaming",
    title: "iPhone 15 Pro Max, 256GB, Titanium Black",
    rating: 4.7,
    price: 989_000,
    oldPrice: 1_050_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/iphone-15-pro",
    description:
      "The most advanced iPhone ever. Featuring a titanium design, A17 Pro chip, and a revolutionary 48MP camera system. Experience the power of Apple's latest innovations with the stunning Super Retina XDR display.",
    specs: [
      { label: "Display", value: '6.7" OLED' },
      { label: "Processor", value: "A17 Pro" },
      { label: "Storage", value: "256GB" },
      { label: "Camera", value: "48MP Main + 12MP Ultra Wide" },
      { label: "Battery", value: "4422mAh" },
      { label: "Material", value: "Titanium frame" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 256,
    stock: 10,
    similarProducts: ["ps5-vr2", "sony-wh1000xm5", "iphone-15-pro"],
  },
  {
    id: "samsung-qled-tv",
    category: "Gaming",
    title: 'Samsung Neo QLED 8K 75", QN900C Smart TV',
    rating: 4.6,
    price: 2_450_000,
    oldPrice: 2_800_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/samsung-qled-8k",
    description:
      "Transform your viewing experience with Samsung's flagship Neo QLED 8K TV. Features Quantum Matrix Technology Pro for precise lighting control and Neural Quantum Processor 8K for unmatched upscaling performance.",
    specs: [
      { label: "Resolution", value: "8K (7680 x 4320)" },
      { label: "Screen Size", value: "75 inches" },
      { label: "HDR", value: "Quantum HDR 4000" },
      { label: "Refresh Rate", value: "120Hz" },
      { label: "Audio", value: "Dolby Atmos" },
      { label: "Smart Platform", value: "Tizen OS" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 45,
    stock: 2,
    similarProducts: ["iphone-15-pro", "macbook-pro-m2", "ps5-vr2"],
  },
  {
    id: "sony-wh1000xm5",
    category: "Gaming",
    title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    rating: 4.8,
    price: 285_000,
    oldPrice: 320_000,
    image: "/images/shop/hero.svg",
    href: "/shop/products/sony-wh1000xm5",
    description:
      "Industry-leading noise cancellation meets premium sound quality. The WH-1000XM5 features advanced processors for unprecedented noise cancellation, crystal clear calls, and up to 30 hours of battery life.",
    specs: [
      { label: "Driver", value: "30mm Carbon Fiber" },
      { label: "Battery Life", value: "30 hours" },
      { label: "Charging", value: "USB-C Fast Charging" },
      { label: "Bluetooth", value: "5.2" },
      { label: "Weight", value: "250g" },
      { label: "Codecs", value: "LDAC, AAC, SBC" },
    ],
    gallery: ["/images/shop/hero.svg", "/images/shop/hero.svg", "/images/shop/hero.svg"],
    reviews: 167,
    stock: 15,
    similarProducts: ["iphone-15-pro", "macbook-pro-m2", "ps5-vr2"],
  },
];
