import type { LeaveRequest, LeaveType } from '../types';

export const DUMMY_LEAVE_TYPES: LeaveType[] = [
  {
    id: 'leave-type-1',
    name: 'Annual Leave',
    days: 20,
    cycle: 'yearly',
    maxLeaveDaysPerRequest: 20,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'leave-type-2',
    name: 'Sick Leave',
    days: 10,
    cycle: 'yearly',
    maxLeaveDaysPerRequest: 10,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'leave-type-3',
    name: 'Maternity Leave',
    days: 90,
    cycle: 'yearly',
    maxLeaveDaysPerRequest: 90,
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const DUMMY_LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'req-1',
    employee: { id: 'emp-1', name: 'John Doe', avatar: '' },
    type: 'Annual Leave',
    startDate: '2026-02-01',
    endDate: '2026-02-05',
    days: 5,
    reason: 'Family vacation to celebrate the new year with relatives.',
    status: 'pending',
    rejectionReason: null,
    createdAt: '2026-01-15T10:30:00Z',
  },
  {
    id: 'req-2',
    employee: { id: 'emp-2', name: 'Jane Smith', avatar: '' },
    type: 'Sick Leave',
    startDate: '2026-01-20',
    endDate: '2026-01-22',
    days: 3,
    reason: 'Medical appointment and recovery from minor illness.',
    status: 'approved',
    rejectionReason: null,
    createdAt: '2026-01-17T09:15:00Z',
  },
  {
    id: 'req-3',
    employee: { id: 'emp-3', name: 'Michael Johnson', avatar: '' },
    type: 'Annual Leave',
    startDate: '2026-03-10',
    endDate: '2026-03-17',
    days: 8,
    reason: 'Overseas trip planned for several months.',
    status: 'pending',
    rejectionReason: null,
    createdAt: '2026-01-10T16:45:00Z',
  },
  {
    id: 'req-4',
    employee: { id: 'emp-4', name: 'Emily Davis', avatar: '' },
    type: 'Maternity Leave',
    startDate: '2026-02-15',
    endDate: '2026-05-15',
    days: 90,
    reason: 'Maternity leave for the birth of my child.',
    status: 'approved',
    rejectionReason: null,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'req-5',
    employee: { id: 'emp-5', name: 'David Brown', avatar: '' },
    type: 'Annual Leave',
    startDate: '2026-01-25',
    endDate: '2026-01-26',
    days: 2,
    reason: 'Personal matters that require immediate attention.',
    status: 'rejected',
    rejectionReason: 'Insufficient leave balance.',
    createdAt: '2026-01-15T13:20:00Z',
  },
];
