import {
  ArrowLeft,
  ArrowRight2 as ArrowRight,
  TickCircle as Check,
  ArrowLeft2 as ChevronLeft,
  ArrowRight3 as ChevronRight,
  CloseCircle as Close,
  Command,
  Card as CreditCard,
  More as DotsVertical,
  Document as File,
  DocumentText as FileText,
  InfoCircle as HelpCircle,
  Category2 as LayoutDashboard,
  Kanban as LayoutKanban,
  Login,
  Moon,
  Image as Photo,
  Add as Plus,
  Setting2 as Settings,
  Bag2 as ShoppingBag,
  Sun1 as Sun,
  Trash,
  User,
  UserOctagon as UserCircle,
  UserEdit,
  UserMinus as UserX,
  Danger as Warning,
} from "iconsax-reactjs";

export type Icon = React.ComponentType<{
  className?: string;
  size?: number;
  variant?: "Linear" | "Outline" | "Bold" | "Broken" | "Bulk" | "TwoTone";
}>;

export const Icons = {
  dashboard: LayoutDashboard,
  logo: Command,
  login: Login,
  close: Close,
  product: ShoppingBag,
  kanban: LayoutKanban,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX,
  post: FileText,
  page: File,
  userPen: UserEdit,
  user2: UserCircle,
  media: Photo,
  settings: Settings,
  billing: CreditCard,
  ellipsis: DotsVertical,
  add: Plus,
  warning: Warning,
  user: User,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  help: HelpCircle,
  sun: Sun,
  moon: Moon,
  check: Check,
};
