import { Calendar2, CardReceive, Element3, People, Profile2User } from "iconsax-reactjs";
import { Clock } from "lucide-react";

export const countries = [
  { value: "afghanistan", label: "🇦🇫 Afghanistan" },
  { value: "albania", label: "🇦🇱 Albania" },
  { value: "algeria", label: "🇩🇿 Algeria" },
  { value: "andorra", label: "🇦🇩 Andorra" },
  { value: "angola", label: "🇦🇴 Angola" },
  { value: "antigua_and_barbuda", label: "🇦🇬 Antigua and Barbuda" },
  { value: "argentina", label: "🇦🇷 Argentina" },
  { value: "armenia", label: "🇦🇲 Armenia" },
  { value: "australia", label: "🇦🇺 Australia" },
  { value: "austria", label: "🇦🇹 Austria" },
  { value: "azerbaijan", label: "🇦🇿 Azerbaijan" },
  { value: "bahamas", label: "🇧🇸 Bahamas" },
  { value: "bahrain", label: "🇧🇭 Bahrain" },
  { value: "bangladesh", label: "🇧🇩 Bangladesh" },
  { value: "barbados", label: "🇧🇧 Barbados" },
  { value: "belarus", label: "🇧🇾 Belarus" },
  { value: "belgium", label: "🇧🇪 Belgium" },
  { value: "belize", label: "🇧🇿 Belize" },
  { value: "benin", label: "🇧🇯 Benin" },
  { value: "bhutan", label: "🇧🇹 Bhutan" },
  { value: "bolivia", label: "🇧🇴 Bolivia" },
  { value: "bosnia_and_herzegovina", label: "🇧🇦 Bosnia and Herzegovina" },
  { value: "botswana", label: "🇧🇼 Botswana" },
  { value: "brazil", label: "🇧🇷 Brazil" },
  { value: "brunei", label: "🇧🇳 Brunei" },
  { value: "bulgaria", label: "🇧🇬 Bulgaria" },
  { value: "burkina_faso", label: "🇧🇫 Burkina Faso" },
  { value: "burundi", label: "🇧🇮 Burundi" },
  { value: "cambodia", label: "🇰🇭 Cambodia" },
  { value: "cameroon", label: "🇨🇲 Cameroon" },
  { value: "canada", label: "🇨🇦 Canada" },
  { value: "cape_verde", label: "🇨🇻 Cape Verde" },
  { value: "central_african_republic", label: "🇨🇫 Central African Republic" },
  { value: "chad", label: "🇹🇩 Chad" },
  { value: "chile", label: "🇨🇱 Chile" },
  { value: "china", label: "🇨🇳 China" },
  { value: "colombia", label: "🇨🇴 Colombia" },
  { value: "comoros", label: "🇰🇲 Comoros" },
  { value: "congo", label: "🇨🇬 Congo" },
  { value: "costa_rica", label: "🇨🇷 Costa Rica" },
  { value: "croatia", label: "🇭🇷 Croatia" },
  { value: "cuba", label: "🇨🇺 Cuba" },
  { value: "cyprus", label: "🇨🇾 Cyprus" },
  { value: "czech_republic", label: "🇨🇿 Czech Republic" },
  { value: "denmark", label: "🇩🇰 Denmark" },
  { value: "djibouti", label: "🇩🇯 Djibouti" },
  { value: "dominica", label: "🇩🇲 Dominica" },
  { value: "dominican_republic", label: "🇩🇴 Dominican Republic" },
  { value: "ecuador", label: "🇪🇨 Ecuador" },
  { value: "egypt", label: "🇪🇬 Egypt" },
  { value: "el_salvador", label: "🇸🇻 El Salvador" },
  { value: "equatorial_guinea", label: "🇬🇶 Equatorial Guinea" },
  { value: "eritrea", label: "🇪🇷 Eritrea" },
  { value: "estonia", label: "🇪🇪 Estonia" },
  { value: "ethiopia", label: "🇪🇹 Ethiopia" },
  { value: "fiji", label: "🇫🇯 Fiji" },
  { value: "finland", label: "🇫🇮 Finland" },
  { value: "france", label: "🇫🇷 France" },
  { value: "gabon", label: "🇬🇦 Gabon" },
  { value: "gambia", label: "🇬🇲 Gambia" },
  { value: "georgia", label: "🇬🇪 Georgia" },
  { value: "germany", label: "🇩🇪 Germany" },
  { value: "ghana", label: "🇬🇭 Ghana" },
  { value: "greece", label: "🇬🇷 Greece" },
  { value: "grenada", label: "🇬🇩 Grenada" },
  { value: "guatemala", label: "🇬🇹 Guatemala" },
  { value: "guinea", label: "🇬🇳 Guinea" },
  { value: "guinea_bissau", label: "🇬🇼 Guinea-Bissau" },
  { value: "guyana", label: "🇬🇾 Guyana" },
  { value: "haiti", label: "🇭🇹 Haiti" },
  { value: "honduras", label: "🇭🇳 Honduras" },
  { value: "hungary", label: "🇭🇺 Hungary" },
  { value: "iceland", label: "🇮🇸 Iceland" },
  { value: "india", label: "🇮🇳 India" },
  { value: "indonesia", label: "🇮🇩 Indonesia" },
  { value: "iran", label: "🇮🇷 Iran" },
  { value: "iraq", label: "🇮🇶 Iraq" },
  { value: "ireland", label: "🇮🇪 Ireland" },
  { value: "israel", label: "🇮🇱 Israel" },
  { value: "italy", label: "🇮🇹 Italy" },
  { value: "jamaica", label: "🇯🇲 Jamaica" },
  { value: "japan", label: "🇯🇵 Japan" },
  { value: "jordan", label: "🇯🇴 Jordan" },
  { value: "kazakhstan", label: "🇰🇿 Kazakhstan" },
  { value: "kenya", label: "🇰🇪 Kenya" },
  { value: "kiribati", label: "🇰🇮 Kiribati" },
  { value: "north_korea", label: "🇰🇵 North Korea" },
  { value: "south_korea", label: "🇰🇷 South Korea" },
  { value: "kuwait", label: "🇰🇼 Kuwait" },
  { value: "kyrgyzstan", label: "🇰🇬 Kyrgyzstan" },
  { value: "laos", label: "🇱🇦 Laos" },
  { value: "latvia", label: "🇱🇻 Latvia" },
  { value: "lebanon", label: "🇱🇧 Lebanon" },
  { value: "lesotho", label: "🇱🇸 Lesotho" },
  { value: "liberia", label: "🇱🇷 Liberia" },
  { value: "libya", label: "🇱🇾 Libya" },
  { value: "liechtenstein", label: "🇱🇮 Liechtenstein" },
  { value: "lithuania", label: "🇱🇹 Lithuania" },
  { value: "luxembourg", label: "🇱🇺 Luxembourg" },
  { value: "madagascar", label: "🇲🇬 Madagascar" },
  { value: "malawi", label: "🇲🇼 Malawi" },
  { value: "malaysia", label: "🇲🇾 Malaysia" },
  { value: "maldives", label: "🇲🇻 Maldives" },
  { value: "mali", label: "🇲🇱 Mali" },
  { value: "malta", label: "🇲🇹 Malta" },
  { value: "marshall_islands", label: "🇲🇭 Marshall Islands" },
  { value: "mauritania", label: "🇲🇷 Mauritania" },
  { value: "mauritius", label: "🇲🇺 Mauritius" },
  { value: "mexico", label: "🇲🇽 Mexico" },
  { value: "micronesia", label: "🇫🇲 Micronesia" },
  { value: "moldova", label: "🇲🇩 Moldova" },
  { value: "monaco", label: "🇲🇨 Monaco" },
  { value: "mongolia", label: "🇲🇳 Mongolia" },
  { value: "montenegro", label: "🇲🇪 Montenegro" },
  { value: "morocco", label: "🇲🇦 Morocco" },
  { value: "mozambique", label: "🇲🇿 Mozambique" },
  { value: "myanmar", label: "🇲🇲 Myanmar" },
  { value: "namibia", label: "🇳🇦 Namibia" },
  { value: "nauru", label: "🇳🇷 Nauru" },
  { value: "nepal", label: "🇳🇵 Nepal" },
  { value: "netherlands", label: "🇳🇱 Netherlands" },
  { value: "new_zealand", label: "🇳🇿 New Zealand" },
  { value: "nicaragua", label: "🇳🇮 Nicaragua" },
  { value: "niger", label: "🇳🇪 Niger" },
  { value: "nigeria", label: "🇳🇬 Nigeria" },
  { value: "norway", label: "🇳🇴 Norway" },
  { value: "oman", label: "🇴🇲 Oman" },
  { value: "pakistan", label: "🇵🇰 Pakistan" },
  { value: "palau", label: "🇵🇼 Palau" },
  { value: "palestine", label: "🇵🇸 Palestine" },
  { value: "panama", label: "🇵🇦 Panama" },
  { value: "papua_new_guinea", label: "🇵🇬 Papua New Guinea" },
  { value: "paraguay", label: "🇵🇾 Paraguay" },
  { value: "peru", label: "🇵🇪 Peru" },
  { value: "philippines", label: "🇵🇭 Philippines" },
  { value: "poland", label: "🇵🇱 Poland" },
  { value: "portugal", label: "🇵🇹 Portugal" },
  { value: "qatar", label: "🇶🇦 Qatar" },
  { value: "romania", label: "🇷🇴 Romania" },
  { value: "russia", label: "🇷🇺 Russia" },
  { value: "rwanda", label: "🇷🇼 Rwanda" },
  { value: "saint_kitts_and_nevis", label: "🇰🇳 Saint Kitts and Nevis" },
  { value: "saint_lucia", label: "🇱🇨 Saint Lucia" },
  { value: "saint_vincent", label: "🇻🇨 Saint Vincent and the Grenadines" },
  { value: "samoa", label: "🇼🇸 Samoa" },
  { value: "san_marino", label: "🇸🇲 San Marino" },
  { value: "sao_tome_and_principe", label: "🇸🇹 São Tomé and Príncipe" },
  { value: "saudi_arabia", label: "🇸🇦 Saudi Arabia" },
  { value: "senegal", label: "🇸🇳 Senegal" },
  { value: "serbia", label: "🇷🇸 Serbia" },
  { value: "seychelles", label: "🇸🇨 Seychelles" },
  { value: "sierra_leone", label: "🇸🇱 Sierra Leone" },
  { value: "singapore", label: "🇸🇬 Singapore" },
  { value: "slovakia", label: "🇸🇰 Slovakia" },
  { value: "slovenia", label: "🇸🇮 Slovenia" },
  { value: "solomon_islands", label: "🇸🇧 Solomon Islands" },
  { value: "somalia", label: "🇸🇴 Somalia" },
  { value: "south_africa", label: "🇿🇦 South Africa" },
  { value: "south_sudan", label: "🇸🇸 South Sudan" },
  { value: "spain", label: "🇪🇸 Spain" },
  { value: "sri_lanka", label: "🇱🇰 Sri Lanka" },
  { value: "sudan", label: "🇸🇩 Sudan" },
  { value: "suriname", label: "🇸🇷 Suriname" },
  { value: "sweden", label: "🇸🇪 Sweden" },
  { value: "switzerland", label: "🇨🇭 Switzerland" },
  { value: "syria", label: "🇸🇾 Syria" },
  { value: "taiwan", label: "🇹🇼 Taiwan" },
  { value: "tajikistan", label: "🇹🇯 Tajikistan" },
  { value: "tanzania", label: "🇹🇿 Tanzania" },
  { value: "thailand", label: "🇹🇭 Thailand" },
  { value: "timor_leste", label: "🇹🇱 Timor-Leste" },
  { value: "togo", label: "🇹🇬 Togo" },
  { value: "tonga", label: "🇹🇴 Tonga" },
  { value: "trinidad_and_tobago", label: "🇹🇹 Trinidad and Tobago" },
  { value: "tunisia", label: "🇹🇳 Tunisia" },
  { value: "turkey", label: "🇹🇷 Turkey" },
  { value: "turkmenistan", label: "🇹🇲 Turkmenistan" },
  { value: "tuvalu", label: "🇹🇻 Tuvalu" },
  { value: "uganda", label: "🇺🇬 Uganda" },
  { value: "ukraine", label: "🇺🇦 Ukraine" },
  { value: "united_arab_emirates", label: "🇦🇪 United Arab Emirates" },
  { value: "united_kingdom", label: "🇬🇧 United Kingdom" },
  { value: "united_states", label: "🇺🇸 United States" },
  { value: "uruguay", label: "🇺🇾 Uruguay" },
  { value: "uzbekistan", label: "🇺🇿 Uzbekistan" },
  { value: "vanuatu", label: "🇻🇺 Vanuatu" },
  { value: "vatican_city", label: "🇻🇦 Vatican City" },
  { value: "venezuela", label: "🇻🇪 Venezuela" },
  { value: "vietnam", label: "🇻🇳 Vietnam" },
  { value: "yemen", label: "🇾🇪 Yemen" },
  { value: "zambia", label: "🇿🇲 Zambia" },
  { value: "zimbabwe", label: "🇿🇼 Zimbabwe" },
];

export const months = [
  { value: "1", label: "January" },
  { value: "2", label: "February" },
  { value: "3", label: "March" },
  { value: "4", label: "April" },
  { value: "5", label: "May" },
  { value: "6", label: "June" },
  { value: "7", label: "July" },
  { value: "8", label: "August" },
  { value: "9", label: "September" },
  { value: "10", label: "October" },
  { value: "11", label: "November" },
  { value: "12", label: "December" },
];

export const NAV_LINKS: NavLink[] = [
  {
    id: 1,
    title: "Hello",
    href: "/",
    type: "link",
  },
  { id: 2, title: "About Me", href: "/about", type: "link" },
  { id: 3, title: "Projects", href: "/projects", type: "link" },
];

export const adminNavItems = [
  {
    name: "Dashboard",
    url: "/admin/dashboard",
    icon: Element3,
  },
  {
    name: "Employees",
    url: "/admin/employees",
    icon: Profile2User,
  },
  {
    id: "teams",
    name: "Teams",
    url: "/admin/teams",
    icon: People,
  },
  {
    id: "resources",
    name: "Resources",
    url: "/admin/resources",
    icon: People,
  },
  {
    id: "payroll",
    name: "Payroll",
    url: "/admin/payroll",
    icon: CardReceive,
  },
  {
    id: "leave",
    name: "Leave Hub",
    url: "/admin/leave",
    icon: Calendar2,
  },
  {
    id: "attendance",
    name: "Attendance",
    url: "/admin/attendance",
    icon: Clock,
  },
];

// Mock options for select fields
export const industryOptions = [
  { value: "Tech Education", label: "Tech Education" },
  { value: "Finance", label: "Finance" },
  { value: "Healthcare", label: "Healthcare" },
  { value: "Retail", label: "Retail" },
];

export const sizeOptions = [
  { value: "small", label: "Small (1-50)" },
  { value: "medium", label: "Medium (51-200)" },
  { value: "large", label: "Large (201-1000)" },
  { value: "enterprise", label: "Enterprise (1000+)" },
];

export const stateOptions = [
  { value: "london", label: "London" },
  { value: "new york", label: "New York" },
  { value: "ontario", label: "Ontario" },
];

export const cityOptions = [
  { value: "Barking", label: "Barking" },
  { value: "manhattan", label: "Manhattan" },
  { value: "toronto", label: "Toronto" },
];

export const genderOptions = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "other", label: "Other" },
];

export const employmentTypeOptions = [
  { value: "full time", label: "Full time" },
  { value: "part time", label: "Part time" },
  { value: "contract", label: "Contract" },
  // { value: "internship", label: "Internship" },
];

export const workModeOptions = [
  { value: "remote", label: "Remote" },
  { value: "onsite", label: "On site" },
  { value: "hybrid", label: "Hybrid" },
];

export const departmentOptions = [
  { value: "engineering", label: "Engineering" },
  { value: "marketing", label: "Marketing" },
  { value: "sales", label: "Sales" },
  { value: "hr", label: "Human Resources" },
  { value: "finance", label: "Finance" },
];

export const roleOptions = [
  { value: "developer", label: "Developer" },
  { value: "designer", label: "Designer" },
  { value: "manager", label: "Manager" },
  { value: "analyst", label: "Analyst" },
  { value: "administrator", label: "Administrator" },
];

export const testimonials = [
  {
    id: 1,
    image: "/images/auth/register-img.svg",
    name: "John Doe",
    position: "Designer",
    message:
      "“TechstudioHR has completely transformed how we manage payroll and employee records. What used to take hours now happens in minutes.”",
    rating: 5,
  },
  {
    id: 2,
    image: "/images/auth/login-img.svg",
    name: "Jane Doe",
    position: "Developer",
    message:
      "“TechstudioHR has completely transformed how we manage payroll and employee records. What used to take hours now happens in minutes.”",
    rating: 2,
  },
  {
    id: 3,
    image: "/images/auth/register-img.svg",
    name: "James Doe",
    position: "Customer Service",
    message:
      "“TechstudioHR has completely transformed how we manage payroll and employee records. What used to take hours now happens in minutes.”",
    rating: 4,
  },
];
